[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pyth_min_ref = "2KKV8Xtcom9DcP273i7r47WpeHsmKTXwxmCfqZJwH9fF"

[programs.localnet]
pyth_min_ref = "2KKV8Xtcom9DcP273i7r47WpeHsmKTXwxmCfqZJwH9fF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/linfish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
